FROM node:20-slim

WORKDIR /app

COPY package.json package-lock.json ./

COPY . .
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
RUN npm ci

EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "--port", "3000"]
