version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - PORT=5001
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - CHOKIDAR_USEPOLLING=true
      - PYTHONUNBUFFERED=1

  grader:
    build: ./grader
    ports:
      - "4999:4999"
    volumes:
      - ./grader:/app
      - /var/run/docker.sock:/var/run/docker.sock 
    depends_on:
      - db 
    environment:
      - PORT=4999
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - POLL_INTERVAL=${POLL_INTERVAL}
      - MAX_WORKERS=${MAX_WORKERS}
      - KEEP_CONTAINERS=true


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend
      - db
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    args:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: UTC
      PGTZ: UTC 
    volumes:
      - judgepgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL} 
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} 
    ports:
      - "5050:80"
    depends_on:
      - db
  
  worker:
    build: ./grader/worker
    entrypoint: [ "echo", "Worker container should not run by default." ]
    profiles: [ "dont-start" ]
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}


volumes:
  judgepgdata:

  # db:
  #   image: postgres:14
  #   restart: always
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: pass
  #     POSTGRES_DB: mydb
  #   ports:
  #     - "5432:5432"
