version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # make sure it's production-safe
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - PORT=5000
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - CORS_ORIGINS=${CORS_ORIGINS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  grader:
    build:
      context: ./grader
      dockerfile: Dockerfile  # ensure it's safe for production
    ports:
      - "4999:4999"
    depends_on:
      - db
    environment:
      - PORT=4999
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - POLL_INTERVAL=${POLL_INTERVAL}
      - MAX_WORKERS=${MAX_WORKERS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # use a two-stage Dockerfile that builds with Vite and serves with NGINX
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "8080:80" # Serve on 8080 so we can use https proxy for 80
    depends_on:
      - backend
      - db
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: UTC
      PGTZ: UTC
    volumes:
      - judgepgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  worker:
    build:
      context: ./grader/worker
    entrypoint: [ "echo", "Worker container should not run by default." ]
    profiles: [ "dont-start" ]
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

volumes:
  judgepgdata:
