FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

# Use environment variable to select which app to run
CMD ["sh", "-c", "flask run --host=0.0.0.0 --port=${PORT:-5000}"]
